version: '3.4'

services:
  calculationengine:
    image: calculationengine-image
    build:
      context: .
      dockerfile: src/Interface/Dockerfile
    expose:
      - "9402"
  nginx:
    image: nginx-image
    build:
        context: .
        dockerfile: src/nginx/Dockerfile
    depends_on:
      - calculationengine
    ports:
        - "92:80"
