version: '3.4'

services:
  calculationengine-api:
    image: calculationengine-image
    build:
      context: .
      dockerfile: src/Interface/Dockerfile
    ports:
      - 9402
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:9402
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
