version: '3.4'

services:
  calculationengine:
    image: calculationengine-image
    build:
      context: .
      dockerfile: src/Interface/Dockerfile
    expose:
      - "9402"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:9402
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
  nginx:
    image: nginx-image
    build:
        context: .
        dockerfile: src/nginx/Dockerfile
    depends_on:
      - calculationengine
    ports:
        - "92:80"
